name: CI And Check

on:
  push:
    branch:
      - main

permissions:
  contents: write

jobs:
  ci_and_check:
    name: CI And Check
    runs-on: ubuntu-latest
    steps:
      - name: Load Checkout
        uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: cargo, clippy, rustfmt
      - name: Cache Cargo Registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Cache Cargo Index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-
      - name: Install Dependencies
        run: cargo fetch
      - name: Run Clippy
        run: cargo clippy
      - name: Run Rustfmt
        run: rustfmt --verbose src/*
      - name: Check
        run: cargo check
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: change: Format .rs file by GithubActions
